urls.py
from django.conf.urls.defaults import *
from django.conf import settings

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',


    #apps
    (r'^', include('app.urls')),
    (r'^blog/', include('blog.urls')),
    (r'^gallery/', include('gallery.urls')),


    #comments
    (r'^comments/', include('django.contrib.comments.urls')),

    #admin
    (r'^admin/doc/', include('django.contrib.admindocs.urls')),
    (r'^admin/', include(admin.site.urls)),

    #static media
    #WARNING: dev only
    url(r'^%s/(?P<path>.*)$' % settings.MEDIA_URL.strip('/'), "django.views.static.serve", {"document_root": settings.MEDIA_ROOT}),

)

menu/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _

class Menu(models.Model):
    title = models.CharField(_('title'), max_length=200)

    def __unicode__(self):
        return self.title


class MenuItem(models.Model):
    menu = models.ForeignKey(Menu, verbose_name=_('menu'))
    title = models.CharField(_('title'), max_length=200)
    url = models.CharField(max_length=1000)
    ordering = models.IntegerField(_('ordering'),default=0)

    class Meta:
        ordering=('ordering',)

    def __unicode__(self):
        return self.title


class SubmenuItem(models.Model):
    menu_item = models.ForeignKey(MenuItem, verbose_name=_('menu item'))
    title = models.CharField(_('title'), max_length=200)
    url = models.CharField(max_length=1000)
    ordering = models.IntegerField(_('ordering'),default=0)

    class Meta:
        ordering=('ordering',)

    def __unicode__(self):
        return self.title

menu/views.py
# Create your views here.

menu/templates/exo/menu/menu.inc.html
{% comment %}
TODO:
{% load menu %}
{% if not menu %}{% load_menu %}{% endif %}
{% endcomment %}

{% for menuitem in menu.menuitem_set.all %}
<li>
    <a href="{{menuitem.url}}">{{menuitem.title}}</a>
    {% if menuitem.submenuitem_set.all %}
    <ul>
    {% for submenuitem in menuitem.submenuitem_set.all %}
        <li><a href="{{submenuitem.url}}">{{submenuitem.title}}</a></li>
    {% endfor %}
    </ul>
    {% endif %}
</li>
{% endfor %}